#!/usr/bin/env python3
"""Build src/qmk/demo/<name>.ts from a vial-qmk keymap directory.

Usage:
  python3 scripts/generateQmkDemo.py <vial-qmk>/keyboards/salicylic_acid3/clickboard_ergomini multi-os clickboardErgoMini

Reads <keyboard>/keyboard.json (LAYOUT order), <keyboard>/keymaps/<keymap>/vial.json
and keymap.c, and writes the xz-compressed definition plus the default keymap
as keycode names, so the demo keyboard behaves like the real firmware.
"""
import base64
import json
import lzma
import re
import sys
from pathlib import Path

keyboard_dir = Path(sys.argv[1])
keymap_name = sys.argv[2]
out_name = sys.argv[3]
keymap_dir = keyboard_dir / "keymaps" / keymap_name

definition = json.load(open(keymap_dir / "vial.json"))
compressed = lzma.compress(json.dumps(definition).encode("utf-8"))

source = open(keymap_dir / "keymap.c").read()
layers = re.findall(r"\[(\d+)\] = LAYOUT\((.*?)\n    \)", source, re.S)
keymap = {}
for index, body in layers:
    names = [t.strip() for t in body.replace("\n", " ").split(",") if t.strip()]
    keymap[int(index)] = names

keyboard = json.load(open(keyboard_dir / "keyboard.json"))
order = [tuple(k["matrix"]) for k in keyboard["layouts"]["LAYOUT"]["layout"]]
for index, names in keymap.items():
    assert len(names) == len(order), f"layer {index}: {len(names)} keys, LAYOUT has {len(order)}"

rows, cols = definition["matrix"]["rows"], definition["matrix"]["cols"]
grids = []
for index in sorted(keymap):
    grid = [["KC_NO"] * cols for _ in range(rows)]
    for (r, c), name in zip(order, keymap[index]):
        grid[r][c] = "KC_TRNS" if name == "_______" else name
    grids.append(grid)

ts = f'''/**
 * Demo keyboard: {definition["name"]}, {keymap_name} keymap, exactly as built from
 * {keyboard_dir.name}/keymaps/{keymap_name} in the vial-qmk fork. The definition is the
 * xz-compressed vial.json the firmware embeds, so the demo exercises the same
 * decoding path as a real keyboard.
 *
 * GENERATED by scripts/generateQmkDemo.py — rerun when the firmware keymap changes.
 */

/** xz-compressed vial.json, base64. */
export const DEMO_DEFINITION_XZ_BASE64 =
  "{base64.b64encode(compressed).decode()}";

/** Keycode names indexed [layer][row][col]. */
export const DEMO_KEYMAP: string[][][] = {json.dumps(grids, indent=1)};
'''
out = Path("src/qmk/demo") / f"{out_name}.ts"
out.write_text(ts)
print(f"{len(compressed)} definition bytes, {len(grids)} layers -> {out}")
