"""
Writes src/qmk/lib/keycodes/vialNames.generated.ts from vial-gui's keycode
tables, so .vil files use the names Vial itself writes and reads.

  python3 scripts/generateVialNames.py /path/to/vial-gui/src/main/python/keycodes

keycodes_v6.py gives every name -> number; keycodes.py lists the keys the
Vial GUI shows (the names its save_layout writes), with their aliases.
"""
import re, runpy, sys, json
from pathlib import Path

d = Path(sys.argv[1])
kc = runpy.run_path(str(d / "keycodes_v6.py"))["keycodes_v6"].kc
src = (d / "keycodes.py").read_text()

gui, aliases = [], {}
for m in re.finditer(r'\bK\(\s*"([^"]+)"(.*?)\)\s*,?\s*$', src, re.M):
    name, rest = m.group(1), m.group(2)
    if name not in kc:
        continue
    gui.append(name)
    a = re.search(r'alias=\[([^\]]*)\]', rest)
    if a:
        for al in re.findall(r'"([^"]+)"', a.group(1)):
            aliases[al] = name

masked = {n: kc[n] for n in kc if n.endswith("(kc)")}
gui_plain = []
seen = set()
for n in gui:
    if n.endswith("(kc)"):
        continue
    if kc[n] in seen:
        continue
    seen.add(kc[n])
    gui_plain.append([n, kc[n]])
all_names = {n: v for n, v in kc.items() if not n.endswith("(kc)") and "{" not in n}
for al, n in aliases.items():
    all_names.setdefault(al, kc[n])

out = Path(__file__).resolve().parent.parent / "src/qmk/lib/keycodes/vialNames.generated.ts"
out.write_text(
    "// Generated by scripts/generateVialNames.py from vial-gui keycodes_v6.py / keycodes.py.\n"
    "// Do not edit by hand.\n\n"
    "/** Names the Vial GUI writes, one per keycode (its save_layout). */\n"
    f"export const VIAL_GUI_NAMES: ReadonlyArray<readonly [string, number]> = {json.dumps(gui_plain)};\n\n"
    "/** Masked families, e.g. LCTL(kc), LT1(kc), LCTL_T(kc): name -> base. */\n"
    f"export const VIAL_MASKED: ReadonlyArray<readonly [string, number]> = {json.dumps(sorted(masked.items(), key=lambda x: x[1]))};\n\n"
    "/** Every name Vial reads, aliases included. */\n"
    f"export const VIAL_ALL_NAMES: ReadonlyArray<readonly [string, number]> = {json.dumps(sorted(all_names.items()))};\n"
)
print(len(gui_plain), len(masked), len(all_names), "->", out)
